[package]
name = "tsk"
version = "0.3.0"
authors = ["matthew seyer <https://github.com/forensicmatt/libtsk-rs>"]
edition = "2018"

[dependencies]
clap = "2"

[build-dependencies]
bindgen = "0.61"

[target.'cfg(windows)'.build-dependencies.winreg]
version = "0.7"
